/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('comments').del()
  await knex('comments').insert([
    { 
      // id: 1,
      user_id: 1, 
      partner_id: 1,
      platform_id:  1,
      taste_point:  0,
      service_point:  0,
      speed_point:  0,
      hygiene_point:  0,
      staff_point:  0,
      like:  0,
      overflow:  0,
      isAnswered:  1,
      comment: "Tebrikler! selfgourmet.com'da ilk 4000 yoruma ulaşan ilk işletme oldunuz."
    },
    {  
      // id: 2,
      user_id: 4, 
      partner_id: 1,
      platform_id:  2,
      taste_point:  3,
      service_point:  2,
      speed_point:  5,
      hygiene_point:  0,
      staff_point:  0,
      like:  999,
      overflow:  1,
      isAnswered:  0,
      comment: "15 dakikada kapıma gelmesi ile eve sipariş sistemi beni şaşırttı, lezzet olarak standart bigmac hiç değişmez ama servise peçete koymamanız eksi puan yazar",
      likers: [1, 2, 3, 4, 5],
    },
    {  
      // id: 3,
      user_id: 5, 
      partner_id: 1,
      platform_id:  2,
      taste_point:  1,
      service_point:  3,
      speed_point:  5,
      hygiene_point:  0,
      staff_point:  0,
      like:  333,
      comment: "Gece canım tatlı çekti ve tek açık yer sizi buldum ama söylediğime pişman oldum. Hızlı gelmesine rağmen Çuros adı altında sattığınız şey rezalet, sağlığa zararlı olduğunu gönül rahatlığı ile söyleyebilirim.",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 4,
      user_id: 2, 
      partner_id: 1,
      platform_id:  1,
      taste_point:  0,
      service_point:  0,
      speed_point:  0,
      hygiene_point:  0,
      staff_point:  0,
      like:  0,
      comment: "%60 cevaplama oranı ile en yüksek cevaplamaya sahip işletmeler arasına girdiniz.",
    },
    {  
      // id: 5,
      user_id: 6, 
      partner_id: 1,
      platform_id:  3,
      taste_point:  5,
      service_point:  3,
      speed_point:  5,
      hygiene_point:  0,
      staff_point:  0,
      like:  975,
      comment: "BigMac her daim yenir. Getiryemek kampanyası ile kaçmaz.",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
      isAnswered:  1,
    },
    {  
      // id: 6,
      user_id: 13, 
      partner_id: 1,
      platform_id:  1,
      taste_point:  5,
      service_point:  5,
      speed_point:  0,
      hygiene_point:  5,
      staff_point:  5,
      like:  833,
      comment: "Karnım Doydu. Personel güleryüzlü. Yoldan geçerken uğradım, uğradığıma deydi. Güzel",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 7,
      user_id: 14, 
      partner_id: 1,
      platform_id:  2,
      taste_point:  1,
      service_point:  1,
      speed_point:  3,
      hygiene_point:  0,
      staff_point:  0,
      like:  132,
      comment: "Yav bunedir, aç kaldım, keşke ekmek felan alıp yiyedim karnım doyardı, tadı tuzuda yoktu",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 8,
      user_id: 15, 
      partner_id: 1,
      platform_id:  1,
      taste_point:  4,
      service_point:  3,
      speed_point: 0,
      hygiene_point:  1,
      staff_point:  2,
      like:  487,
      comment: "İzmir şubenizdeki elemanlar daha ilgili ve İzmirde yemek daha keyifli.Ayrıca masaya ketçap dökülmüştü kimse temizlemedi.",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
      isAnswered:  1,
    },
    {  
      // id: 9,
      user_id: 16, 
      partner_id: 1,
      platform_id:  2,
      taste_point:  1,
      service_point:  1,
      speed_point:  1,
      hygiene_point:  0,
      staff_point:  0,
      like:  999,
      overflow:  1,
      comment: "Donat Sevmem",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
      isAnswered:  1,
    },
    {  
      // id: 10,
      user_id: 17, 
      partner_id: 1,
      platform_id:  3,
      taste_point:  3,
      service_point:  2,
      speed_point:  4,
      hygiene_point:  0,
      staff_point:  0,
      like:  517,
      comment: "Arby's yemekten bıkınca arada BigMac yerim. //test-comment",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 11,
      user_id: 18, 
      partner_id: 1,
      platform_id:  1,
      taste_point:  3,
      service_point:  3,
      speed_point:  0,
      hygiene_point:  5,
      staff_point:  5,
      like:  113,
      comment: "Popeyes tavuklarının yanında BigMac enfessssss.",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 12,
      user_id: 16, 
      partner_id: 2,
      platform_id:  2,
      taste_point:  1,
      service_point:  2,
      speed_point:  3,
      hygiene_point:  0,
      staff_point:  0,
      like:  870,
      comment: "Donat Sevmem",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 13,
      user_id: 16, 
      partner_id: 3,
      platform_id:  4,
      taste_point:  2,
      service_point:  3,
      speed_point:  4,
      hygiene_point:  0,
      staff_point:  0,
      like:  989,
      comment: "Donat Sevmem",
      likers: [1, 2, 3, 4, 5, 6, 7, 8],
    },
    {  
      // id: 14,
      user_id: 1, 
      partner_id: 3,
      platform_id:  1,
      taste_point:  0,
      service_point:  0,
      speed_point:  0,
      hygiene_point:  0,
      staff_point:  0,
      like:  0,
      isAnswered:  1,
      comment: "Tebrikler! selfgourmet.com ile işbirliğiniz sonucu bugün 2000 kişi sizi tercih etti.",
    },
    {  
      // id: 15,
      user_id: 15, 
      partner_id: 2,
      platform_id:  3,
      taste_point:  5,
      service_point:  5,
      speed_point:  5,
      hygiene_point:  0,
      staff_point:  0,
      like:  424,
      comment: "Yediğim en iyi whopper menü sanırım bu BK şubesindeydi.",
    },

    //GAZİLİ OLMAK AYRICALIKTIR
    {  
      // id: 16,
      user_id: 1, 
      partner_id: 9,
      platform_id:  1,
      taste_point:  5,
      service_point:  5,
      speed_point:  5,
      hygiene_point:  5,
      staff_point:  5,
      like:  999,
      comment: "Gazili Olmak Ayrıcalıktır",
    },
    {  
      // id: 16,
      user_id: 2, 
      partner_id: 9,
      platform_id:  1,
      taste_point:  5,
      service_point:  5,
      speed_point:  5,
      hygiene_point:  5,
      staff_point:  5,
      like:  999,
      comment: "Gazili Olmak Ayrıcalıktır",
    },
    {  
      // id: 16,
      user_id: 3, 
      partner_id: 9,
      platform_id:  1,
      taste_point:  5,
      service_point:  5,
      speed_point:  5,
      hygiene_point:  5,
      staff_point:  5,
      like:  999,
      comment: "Gazili Olmak Ayrıcalıktır",
    },
    {  
      // id: 16,
      user_id: 19, 
      partner_id: 9,
      platform_id:  1,
      taste_point:  5,
      service_point:  5,
      speed_point:  5,
      hygiene_point:  5,
      staff_point:  5,
      like:  999,
      comment: "Gazili Olmak Ayrıcalıktır",
    },
  ]).then(console.log(" - - - COMMENT: Seed Run Successful - - - "));
};
